using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using WordSend;

namespace BibleFileLib
{
	/// <summary>
	/// This subclass overrides various methods to generate HTML in a frame system.
	/// At the root, index.htm is a frame containing a navigation pane, Navigation.htm, above another frame page, Root.htm.
	/// Root.htm contains a left pane ChapterIndex.htm, and a right pane introduction.htm.
	/// 
	/// ChapterIndex.htm (separately generated by UsfxToChapterIndex) contains links to a set of parallel frame files, one set for each chapter:
	/// main_IDNN.htm is the top-level frame for book ID chapter NN (there's also main_IDTOC.htm for a table of contents, and sometimes main_IDIntroduction.htm
	/// for an introduction to the book). They follow the pattern:
	/// main_IDNN.htm is a frame holding Navigation.htm above Root_IDNN.htm,
	/// Root_IDNN.htm is a frame holding ChapterIndex.htm beside IDNN.htm, the actual chapter content.
	/// 
	/// The actual content of IDNN.htm is also modified by overrides here, so that it does not contain a full set of navigation controls,
	/// but just Previous, Next, and Show Navigation Panes buttons. (JavaScript should change the Show Navigation Panes button to
	/// Hide Navigation Panes when the page is properly framed.)
	/// </summary>
	public class UsfxToFramedHtmlConverter : usfxToHtmlConverter
	{
		private const string MainFramePrefix = "frame_"; // Top level frame files, pair navigation with interior frame
		private const string InteriorFramePrefix = "root_"; // interior frame files, pair chapter index with main content file

		/// <summary>
		/// Return the frame file to use for the specified book and chapter (including chapter 0 for the table of contents).
		/// This needs to be consistent with MainFileLinkTarget, but unfortunately we can't call that, because this method
		/// needs to be static, while the other needs to be virtual.
		/// </summary>
		/// <param name="bookId"></param>
		/// <param name="chap"></param>
		/// <returns></returns>
		public static string TopFrameName(string bookId, int chap)
		{
			return MainFramePrefix + HtmName(bookId, chap);
		}

		/// <summary>
		/// Return the file name to use as a link target when linking to the specified main-pane file.
		/// Overridden here to link to the frame we generate around that file.
		/// This needs to be consistent with TopFrameName, but unfortunately we can't make that call this, because this method
		/// needs to be virtual, while the other needs to be static.
		/// </summary>
		/// <param name="mainFileName"></param>
		/// <returns></returns>
		protected override string MainFileLinkTarget(string mainFileName)
		{
			return MainFramePrefix + mainFileName;
		}

		/// <summary>
		/// Overrride for now to generate a frame for the introduction. Later we may generate the introduction itself, or copy one if found...
		/// </summary>
		/// <param name="translationId"></param>
		/// <param name="indexHtml"></param>
		/// <param name="goText"></param>
		protected override void GenerateIndexFile(string translationId, string indexHtml, string goText)
		{
			string indexFilePath = Path.Combine(htmDir, IndexFileName);
			string rootFileName = "root.htm";
			string rootFilePath = Path.Combine(htmDir, rootFileName);
			WriteFrameFile(indexFilePath, "rows=\"35, *\"", true, "navigation", "Navigation.htm", "body", rootFileName, null);
			WriteFrameFile(rootFilePath, "cols=\"20%,80%\"", false, "index", UsfxToChapterIndex.ChapIndexFileName, "main", "Introduction.htm", null);
		}

		protected override void MakeFramesFor(string htmPath)
		{
			string htmName = Path.GetFileName(htmPath);
			string directory = Path.GetDirectoryName(htmPath);
			var topFrameName = MainFramePrefix + htmName;
			var topFramePath = Path.Combine(directory, topFrameName);
			var interiorFrameName = InteriorFramePrefix + htmName;
			var interiorFramePath = Path.Combine(directory, interiorFrameName);
			WriteFrameFile(topFramePath, "rows=\"35, *\" onload=\"onLoad()\"", true, "navigation", "Navigation.htm", "body", interiorFrameName, "frameFuncs.js");
			WriteFrameFile(interiorFramePath, "cols=\"20%,80%\"", false, "index", UsfxToChapterIndex.ChapIndexFileName, "main", htmName, null);
		}

		/// <summary>
		/// Creaete a frame file according to the parameters given
		/// </summary>
		/// <param name="framePath">Where to put the resulting file</param>
		/// <param name="frameSetParams">params for the frameset element, typically specifies layout of rows or columns</param>
		/// <param name="suppressFirstFrameScroll">true to put scrolling="no" on the first frame</param>
		/// <param name="firstFrameName"></param>
		/// <param name="firstFile">to put in the first frame</param>
		/// <param name="secondFrameName"></param>
		/// <param name="secondFile">to put in the second one.</param>
		private void WriteFrameFile(string framePath, string frameSetParams, bool suppressFirstFrameScroll, string firstFrameName, string firstFile, string secondFrameName, string secondFile, string javaScriptFile)
		{
			var htmFrame = new StreamWriter(framePath, false, Encoding.UTF8);
			htmFrame.WriteLine(
				"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
			htmFrame.WriteLine("<html xmlns:msxsl=\"urn:schemas-microsoft-com:xslt\" xmlns:user=\"urn:nowhere\">");
			htmFrame.WriteLine("<head>");
			htmFrame.WriteLine("<META http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
			htmFrame.WriteLine("<meta name=\"viewport\" content=\"width=device-width\" />");
			if (!string.IsNullOrEmpty(javaScriptFile))
				htmFrame.WriteLine("<script src=\"" + javaScriptFile + "\" type=\"text/javascript\"></script>");
			htmFrame.WriteLine("<frameset " + frameSetParams + ">");
			string suppressScroll = suppressFirstFrameScroll ? " scrolling=\"no\"" : "";
			htmFrame.WriteLine(" <frame name=\"" + firstFrameName + "\" src=\"" + firstFile + "\"" + suppressScroll + ">");
			htmFrame.WriteLine(" <frame name=\"" + secondFrameName + "\" src=\"" + secondFile + "\"/>");
			htmFrame.WriteLine(" <noframes>");
			htmFrame.WriteLine(" <body>");
			// Could make this localizable, but we want it short...making lots of these files, and unlikely to be seen
			htmFrame.WriteLine(" <p>This needs a frame-capable browser.</p>");
			htmFrame.WriteLine(" </body>");
			htmFrame.WriteLine(" </noframes>");
			htmFrame.WriteLine("</frameset>");
			htmFrame.WriteLine("</html>");
			htmFrame.Close();
		}
	}
}
